---
title: "RSF"
output: html_document
date: "2023-10-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}

### Prepare the work space
library(tidyverse)
library(dplyr)
library(scales)
library(beepr)
library(lubridate)
library(ResourceSelection)
library(RColorBrewer)
library(cowplot)
library(colorBlindness)
library(kableExtra)
library(lme4)
library(stats)
library(DHARMa)

getwd()
# "C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/Documents/1. PhD_Main/GitHub_link/Nittedal/SpatialAndMorphology_MBRA_MMYS"

output <- "C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/1. Nittedal 2018-2020/Nittedal_Main/Analyses/Outputs"

file.name <- "RSF"

todays_date <- Sys.Date()
 
dir.name <- str_c(output,"/", file.name, "_", todays_date)
dir.name
 
output_today <- dir.name
output_today

dir.create(output_today)
output_today


```


```{r}

## Covariates from LiDAR data prepared by Hans Ole 
vars <- readRDS("C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/1. Nittedal 2018-2020/Nittedal_Main/Analyses/Inputs/SpatialData/vars_dist45_v3.rds")

#Used and available positions - just for referencing. 
# rsf.data <- read_csv("C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/1. Nittedal 2018-2020/Nittedal_Main/Analyses/Outputs/HomeRangeExploration_2023-09-28/used_available_pts_combined95KE.csv", 
#      col_types = cols(...1 = col_skip()))

summary(vars)
str(vars) # sf data frame
# 16522 observations of 47 variables 

names(vars)
# [1] "BatID"             "Easting"           "Northing"          "used"              "Species"          
#  [6] "UTM"               "Hmax"              "Hmean"             "Hsd"               "Hcv"              
# [11] "Hkurt"             "Hskewness"         "H10"               "H20"               "H30"              
# [16] "H40"               "H50"               "H60"               "H70"               "H80"              
# [21] "H90"               "H95"               "D0"                "D1"                "D2"               
# [26] "D3"                "D4"                "D5"                "D6"                "D7"               
# [31] "D8"                "D9"                "gap3.n"            "gap3.mean.area"    "gap3.sd.area"     
# [36] "gap3.sum.area"     "gap5.n"            "gap5.mean.area"    "gap5.sd.area"      "gap5.sum.area"    
# [41] "ttops.n"           "crown.mean.size"   "crown.sd.size"     "ttops.mean.height" "ttops.sd.height"  
# [46] "water.distance"    "water.objtype"     "YOD"               "DIST"              "geom"           

## For writing descriptions of each variable 

mettext <- as.data.frame(names(vars))
# write.csv(mettext, "~mettext.csv") # 15.11.2023
```

# Housekeeping of LiDAR data 

```{r}
str(vars)
summary(vars)


# Hans Ole: HOW TO DEAL WITH NAs:
dt <- vars
summary(dt[is.na(dt$Hmean),])
dt$H10[is.na(dt$Hmax)] <- 0.5
dt$Hmean[is.na(dt$Hmean)] <- 0.5
dt$H10[is.na(dt$H10)] <- 0.5
dt$H20[is.na(dt$H20)] <- 0.5
dt$H30[is.na(dt$H30)] <- 0.5
dt$H40[is.na(dt$H40)] <- 0.5
dt$H50[is.na(dt$H50)] <- 0.5
dt$H60[is.na(dt$H60)] <- 0.5
dt$H70[is.na(dt$H70)] <- 0.5
dt$H80[is.na(dt$H80)] <- 0.5
dt$H90[is.na(dt$H90)] <- 0.5
dt$H95[is.na(dt$H95)] <- 0.5
set.seed(123)
un <- runif(10000)

dt$Hsd[is.na(dt$Hsd)] <- sd(un)
dt$Hcv[is.na(dt$Hcv)] <- dt$Hsd[is.na(dt$Hcv)] / dt$Hmean[is.na(dt$Hcv)]
dt$crown.mean.size[is.na(dt$crown.mean.size)] <- 0
dt$ttops.mean.height[is.na(dt$ttops.mean.height)] <- 0

dt$gap5.sd.area[is.na(dt$gap5.sd.area)] <- 0
dt$gap3.sd.area[is.na(dt$gap3.sd.area)] <- 0
dt$crown.sd.size[is.na(dt$crown.sd.size)] <- 0
dt$ttops.sd.height[is.na(dt$ttops.sd.height)] <- 0
summary(dt)

# Hmax -Inf = 0.5
dt$Hmax[dt$Hmax == "-Inf"] <- 0.5

## NAs for Hkurt and Hskewness: 
#  Generate a uniform distribution between 0 and 1 and compute the value of that

# Hkurt NA = -1.183527 
dt$Hkurt[is.na(dt$Hkurt)] <- -1.183527 

# Hskewness NA = 0.004507174 
dt$Hskewness[is.na(dt$Hskewness)] <- -0.004507174 


dt$Species=as.factor(dt$Species)
dt$BatID=as.factor(dt$BatID)
dt$water.objtype=as.factor(dt$water.objtype)

dt$YOD[is.na(dt$YOD)] <- "Undetected"
dt$YOD=as.factor(dt$YOD)

# 16522 obs of 23 vars 

dt1 <- dt # Use this to scale all continuous numerical data besides distance to water 

dt1[,7:45]=scale(dt1[,7:45], scale=TRUE) #

names(dt1)

# Make one large complex model with all variables

# If the NAs cause too many issues, discard all NAs and try again.

################################################################################

# Hmax
fit1 = glmer(used ~ Species + Hmax + Hmax*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0) 
# Hmean
fit2 = glmer(used ~ Species + Hmean + Hmean*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0) 

# Hsd 
fit3 = glmer(used ~ Species + Hsd + Hsd*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0) 
# boundary (singular) fit: see help('isSingular') 

# Hcv
fit4 = glmer(used ~ Species + Hcv + Hcv*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0) 
# boundary (singular) fit: see help('isSingular') 

# Hkurt
fit5 = glmer(used ~ Species + Hkurt + Hkurt*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0) 
# boundary (singular) fit: see help('isSingular') 

# Hskewness
fit6 = glmer(used ~ Species + Hskewness + Hskewness*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0) 
# boundary (singular) fit: see help('isSingular') 

# H10
fit7 = glmer(used ~ Species + H10 + H10*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0) 
# boundary (singular) fit: see help('isSingular') 

# H20
fit8 = glmer(used ~ Species + H20 + H20*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0) 
# boundary (singular) fit: see help('isSingular') 

# H30
fit9 = glmer(used ~ Species + H30 + H30*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0) 
# boundary (singular) fit: see help('isSingular') 

# H40
fit10 = glmer(used ~ Species + H40 + H40*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0) 
# boundary (singular) fit: see help('isSingular') 

# H50
fit11 = glmer(used ~ Species + H50 + H50*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0) 

# H60
fit12 = glmer(used ~ Species + H60 + H60*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0) 

# H70
fit13 = glmer(used ~ Species + H70 + H70*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0) 

# H80
fit14 = glmer(used ~ Species + H80 + H80*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0) 

# H90
fit15 = glmer(used ~ Species + H90 + H90*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0) 
# boundary (singular) fit: see help('isSingular')

# H95
fit16 = glmer(used ~ Species + H95 + H95*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0) 
# boundary (singular) fit: see help('isSingular')


fit17 = glmer(used ~ Species + D0 + D0*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0)
# boundary (singular) fit: see help('isSingular')

fit18 = glmer(used ~ Species + D1 + D1*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0)
# boundary (singular) fit: see help('isSingular')

fit19 = glmer(used ~ Species + D2 + D2*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0)
# boundary (singular) fit: see help('isSingular')

fit20 = glmer(used ~ Species + D3 + D3*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0)
# boundary (singular) fit: see help('isSingular')

fit21 = glmer(used ~ Species + D4 + D4*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0)

fit22 = glmer(used ~ Species + D5 + D5*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0)
#boundary (singular) fit: see help('isSingular')

fit23 = glmer(used ~ Species + D6 + D6*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0)
# boundary (singular) fit: see help('isSingular')

fit24 = glmer(used ~ Species + D7 + D7*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0)
# boundary (singular) fit: see help('isSingular')

fit25 = glmer(used ~ Species + D8 + D8*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0)
# boundary (singular) fit: see help('isSingular')

fit26 = glmer(used ~ Species + D9 + D9*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0)
# boundary (singular) fit: see help('isSingular')

fit27 = glmer(used ~ Species + gap3.n + gap3.n*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0)
# boundary (singular) fit: see help('isSingular')

fit28 = glmer(used ~ Species + gap3.mean.area + gap3.mean.area*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0)
# boundary (singular) fit: see help('isSingular')

fit29 = glmer(used ~ Species + gap3.sd.area + gap3.sd.area*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0)
# boundary (singular) fit: see help('isSingular')

fit30 = glmer(used ~ Species + gap3.sum.area + gap3.sum.area*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0)
# boundary (singular) fit: see help('isSingular')

fit31 = glmer(used ~ Species + gap5.n + gap5.n*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0)
# boundary (singular) fit: see help('isSingular')

fit32 = glmer(used ~ Species + gap5.mean.area + gap5.mean.area*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0)
# boundary (singular) fit: see help('isSingular')

fit33 = glmer(used ~ Species + gap5.sd.area + gap5.sd.area*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0)
# boundary (singular) fit: see help('isSingular')

fit34 = glmer(used ~ Species + gap5.sum.area + gap5.sum.area*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0)
# boundary (singular) fit: see help('isSingular')

fit35 = glmer(used ~ Species + ttops.n + ttops.n*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0)
# boundary (singular) fit: see help('isSingular') 

fit36 = glmer(used ~ Species + crown.mean.size + crown.mean.size*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0)
# boundary (singular) fit: see help('isSingular') 

fit37 = glmer(used ~ Species + crown.sd.size + crown.sd.size*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0)
# boundary (singular) fit: see help('isSingular') 

fit38 = glmer(used ~ Species + ttops.mean.height + ttops.mean.height*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0)
# boundary (singular) fit: see help('isSingular') 

fit39 = glmer(used ~ Species + ttops.sd.height + ttops.sd.height*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0)
# boundary (singular) fit: see help('isSingular') 

fit40 = glmer(used ~ Species + water.distance + water.distance*Species + (1|BatID), data=dt1,
              family=binomial(link="logit"),nAGQ = 0)

names(dt)

# error message "boundary (singular) fit: see help('isSingular')" interpretted as: 
# Your model did fit, but it generated that warning because your random effects are very small. 

################################################################################

summary(fit1) 
summary(fit2) 
summary(fit3) 
summary(fit4) 
summary(fit5) 
summary(fit6)
summary(fit7)
summary(fit8)
summary(fit9)
summary(fit10) 
summary(fit11)
summary(fit12) 
summary(fit13)
summary(fit14)
summary(fit15)
summary(fit16)
summary(fit17) 
summary(fit18)
summary(fit19)
summary(fit20)
summary(fit21)
summary(fit22)
summary(fit23)
summary(fit24)
summary(fit25)
summary(fit26)
summary(fit27)
summary(fit28)
summary(fit29)
summary(fit30)
summary(fit31)
summary(fit32)
summary(fit33)
summary(fit34)
summary(fit35)
summary(fit36)
summary(fit37)
summary(fit38)
summary(fit39)
#                                         Fixed effects:
#                             Estimate Std. Error z value Pr(>|z|)  
# 1 Hmax                     0.54393    0.04829  11.263   <2e-16 ***
# 2 Hmean                    0.46300    0.03950  11.721   <2e-16 ***
# 3 Hsd                      0.48800    0.04226  11.547   <2e-16 ***
# 4 Hcv                     -0.06906    0.04110  -1.680   0.0929 .
# 5 Hkurt                   -0.203448   0.071384  -2.850  0.00437 ** 
# 6 Hskewness               -0.22055    0.04511  -4.890 1.01e-06 ***
# 7 H10                      0.23860    0.03590   6.647    3e-11 ***
# 8 H20                      0.32616    0.03664   8.901   <2e-16 ***
# 9 H30                      0.36262    0.03750   9.669   <2e-16 ***
#10 H40                      0.4046948  0.0382771  10.573   <2e-16 ***
#11 H50                      0.4586793  0.0391807  11.707   <2e-16 ***
#12 H60                      0.48669    0.04032  12.069   <2e-16 ***
#13 H70                      0.49908    0.04135  12.070   <2e-16 ***
#14 H80                      0.50816    0.04249  11.958  < 2e-16 ***
#15 H90                      0.51921    0.04374  11.869  < 2e-16 ***
#16 H95                      0.55640    0.04513  12.329   <2e-16 ***
#17 D0                       0.01242    0.03960   0.314  0.75370 
#18 D1                       0.01567    0.03968   0.395  0.69295
#19 D2                       0.01722    0.03992   0.431  0.66625 
#20 D3                       0.02071    0.04026   0.514  0.60701 
#21 D4                      0.02433    0.04068   0.598  0.54984 
#22 D5                      0.03233    0.04113   0.786  0.43180    
#23 D6                      0.03934    0.04183   0.940  0.3470
#24 D7                      0.03999    0.04292   0.932  0.35147
#25 D8                      0.02920    0.04351   0.671  0.50214 
#26 D9                     -0.006788   0.042609  -0.159  0.87343
#27 gap3.n                 -0.02348    0.04430  -0.530    0.596  
#28 gap3.mean.area         -0.28471    0.04229  -6.732 1.67e-11 *** 
#29 gap3.sd.area            0.13867    0.03288   4.218 2.47e-05 ***
#30 gap3.sum.area          -0.07614    0.04056  -1.877  0.06048 .  
#31 gap5.n                  0.01523    0.04439   0.343    0.731 
#32 gap5.mean.area         -0.37995    0.04337  -8.761   <2e-16 ***
#33 gap5.sd.area            0.14609    0.03293   4.436 9.17e-06 ***
#34 gap5.sum.area          -0.08332    0.04044  -2.060  0.03939 *  
#35 ttops.n                -0.03449    0.04252  -0.811  0.41723 
#36 crown.mean.size         0.034706   0.025866   1.342    0.180
#37 crown.sd.size           0.05820    0.02944   1.977   0.0481 *  
#38 ttops.mean.height       0.55398    0.04489  12.340   <2e-16 ***
#39 ttops.sd.height         0.32153    0.04010   8.019 1.07e-15 ***
#40 water.distance         -0.0026756  0.0003163  -8.460   <2e-16 ***

# Try including:
# hmax, D7, D8, gap3.mean.area, gap3.sum.area, gap5.mean.area, gap5.sum.area, ttops.n  

              
fit = glmer(used ~ Species + hmax + D7 + D8 + 
              gap3.mean.area + gap3.sum.area +
              gap5.mean.area + gap5.sum.area + ttops.n +
              hmax*Species +
              D7*Species +
              D8*Species + 
              gap3.mean.area*Species +
              gap3.sum.area*Species +
              gap5.n*Species +
              gap5.mean.area*Species +
              gap5.sum.area*Species +
              ttops.n*Species + (1|BatID), data=var1,
              family=binomial(link="logit"),nAGQ = 0)

summary(fit)

summary(vars)
# Correlation matrix not shown by default, as p = 20 > 12.
# Use print(x, correlation=TRUE)  or
#     vcov(x)        if you need it

# Fixed effects:
#                                     Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                        -3.031109   0.203818 -14.872  < 2e-16 ***
# SpeciesM.mystacinus                -0.857410   0.326958  -2.622  0.00873 ** 
# hmax                                0.062171   0.006577   9.452  < 2e-16 ***
# D7                                  0.475638   0.519333   0.916  0.35974    
# D8                                 -0.985025   0.487519  -2.020  0.04333 *  
# gap3.mean.area                      0.073531   0.142566   0.516  0.60602    
# gap3.sum.area                      -0.806492   0.468243  -1.722  0.08500 .  
# gap5.mean.area                     -0.374586   0.137849  -2.717  0.00658 ** 
# gap5.sum.area                      -0.116578   0.478079  -0.244  0.80735    
# ttops.n                            -0.014025   0.003039  -4.615 3.93e-06 ***
# gap5.n                             -0.289579   0.101587  -2.851  0.00436 ** 
# SpeciesM.mystacinus:hmax            0.025590   0.010505   2.436  0.01486 *  
# SpeciesM.mystacinus:D7              1.697006   0.745901   2.275  0.02290 *  
# SpeciesM.mystacinus:D8             -0.925983   0.683899  -1.354  0.17574    
# SpeciesM.mystacinus:gap3.mean.area  0.189162   0.207218   0.913  0.36131    
# SpeciesM.mystacinus:gap3.sum.area   1.157127   0.667590   1.733  0.08304 .  
# SpeciesM.mystacinus:gap5.n          0.361017   0.132003   2.735  0.00624 ** 
# SpeciesM.mystacinus:gap5.mean.area  0.088962   0.198956   0.447  0.65477    
# SpeciesM.mystacinus:gap5.sum.area  -0.134643   0.683743  -0.197  0.84389    
# SpeciesM.mystacinus:ttops.n         0.005212   0.004365   1.194  0.23250    
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

drop1(fit, test = "Chi")
# boundary (singular) fit: see help('isSingular')
# boundary (singular) fit: see help('isSingular')
# boundary (singular) fit: see help('isSingular')
# Single term deletions
# 
# Model:
# used ~ Species + hmax + D7 + D8 + gap3.mean.area + gap3.sum.area + 
#     gap5.mean.area + gap5.sum.area + ttops.n + hmax * Species + 
#     D7 * Species + D8 * Species + gap3.mean.area * Species + 
#     gap3.sum.area * Species + gap5.n * Species + gap5.mean.area * 
#     Species + gap5.sum.area * Species + ttops.n * Species + (1 | 
#     BatID)
#                        npar    AIC    LRT  Pr(Chi)   
# <none>                      9599.2                   
# Species:hmax              1 9603.2 5.9726 0.014530 * 
# Species:D7                1 9602.4 5.1938 0.022667 * 
# Species:D8                1 9599.0 1.8165 0.177730   
# Species:gap3.mean.area    1 9598.0 0.8306 0.362094   
# Species:gap3.sum.area     1 9600.2 2.9522 0.085760 . 
# Species:gap5.n            1 9604.7 7.4534 0.006332 **
# Species:gap5.mean.area    1 9597.4 0.1993 0.655289   
# Species:gap5.sum.area     1 9597.3 0.0377 0.846078   
# Species:ttops.n           1 9598.6 1.4117 0.234780   
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1


fit.a = glmer(used ~ Species + hmax + D7 + 
              gap3.sum.area +
              gap5.mean.area +
              gap5.n +
              hmax*Species +
              D7*Species +
              gap3.sum.area*Species +
              gap5.n*Species +
              (1|BatID), data=var1,
              family=binomial(link="logit"),nAGQ = 0)

summary(fit.a)

#      AIC      BIC   logLik deviance df.resid 
#   9679.2   9771.7  -4827.6   9655.2    16510 
# 
# Scaled residuals: 
#     Min      1Q  Median      3Q     Max 
# -3.9606 -0.3588 -0.3016 -0.2124  8.3606 
# 
# Random effects:
#  Groups Name        Variance Std.Dev.
#  BatID  (Intercept) 0.002391 0.0489  
# Number of obs: 16522, groups:  BatID, 21

# Fixed effects:
#                                    Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                       -3.746945   0.159518 -23.489  < 2e-16 ***
# SpeciesM.mystacinus               -0.617348   0.248873  -2.481 0.013117 *  
# hmax                               0.063102   0.006364   9.916  < 2e-16 ***
# D7                                -0.472274   0.111940  -4.219 2.45e-05 ***
# gap3.sum.area                     -0.490264   0.135013  -3.631 0.000282 ***
# gap5.mean.area                    -0.113331   0.058367  -1.942 0.052175 .  
# gap5.n                            -0.326123   0.086226  -3.782 0.000155 ***
# SpeciesM.mystacinus:hmax           0.024180   0.009996   2.419 0.015568 *  
# SpeciesM.mystacinus:D7             0.683922   0.130930   5.224 1.75e-07 ***
# SpeciesM.mystacinus:gap3.sum.area  1.071932   0.163935   6.539 6.20e-11 ***
# SpeciesM.mystacinus:gap5.n         0.550539   0.111179   4.952 7.35e-07 ***
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
# 
# Correlation of Fixed Effects:
#             (Intr) SpcsM. hmax   D7     gp3.s. gp5.m. gap5.n SpcM.: SM.:D7 SM.:3.
# SpcsM.mystc -0.631                                                               
# hmax        -0.960  0.604                                                        
# D7           0.018  0.002  0.028                                                 
# gap3.sum.ar -0.142  0.137  0.184  0.640                                          
# gap5.mean.r -0.102 -0.034  0.114 -0.135 -0.464                                   
# gap5.n      -0.063  0.042  0.091 -0.146  0.465 -0.009                            
# SpcsM.myst:  0.597 -0.968 -0.621 -0.036 -0.179  0.061 -0.059                     
# SpcsM.my:D7 -0.003 -0.060 -0.038 -0.838 -0.490 -0.009  0.126  0.094              
# SpcsM.m:3..  0.153 -0.278 -0.192 -0.479 -0.659  0.027 -0.380  0.332  0.662       
# SpcsM.my:5.  0.051 -0.093 -0.073  0.117 -0.351 -0.015 -0.775  0.116 -0.074  0.572

```


## Sketch model fit for model  to understand what the model is telling us 

Ran into issues with using the glm() function. From what I could read online troubleshooting this error may involve uninstalling and reinstalling R which I would like to avoid... 
```{r}
############################################################

##refitting model with GLM to sketch results

fit.x <- glm(used ~ Species + hmax + D7 + 
              gap3.sum.area +
              gap5.mean.area +
              gap5.n +
              hmax*Species +
              D7*Species +
              gap3.sum.area*Species +
              gap5.n*Species, family=binomial(), data=var1)

summary(fit.x)
# Coefficients:
#                                    Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                       -3.123896   0.177948 -17.555  < 2e-16 ***
# SpeciesM.mystacinus               -0.471452   0.245765  -1.918 0.055072 .  
# hmax                               0.064046   0.006310  10.150  < 2e-16 ***
# D8                                -1.528826   0.339763  -4.500 6.81e-06 ***
# gap3.sum.area                     -0.936956   0.149551  -6.265 3.73e-10 ***
# gap5.mean.area                    -0.202879   0.058935  -3.442 0.000577 ***
# ttops.n                           -0.012984   0.001790  -7.254 4.03e-13 ***
# gap5.n                            -0.290077   0.087132  -3.329 0.000871 ***
# D7                                 1.022709   0.358025   2.857 0.004283 ** 
# SpeciesM.mystacinus:hmax           0.020468   0.009897   2.068 0.038627 *  
# SpeciesM.mystacinus:D7             0.848583   0.142466   5.956 2.58e-09 ***
# SpeciesM.mystacinus:gap3.sum.area  1.079950   0.168810   6.397 1.58e-10 ***
# SpeciesM.mystacinus:gap5.n         0.418130   0.112878   3.704 0.000212 ***
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
# 
# (Dispersion parameter for binomial family taken to be 1)
# 
#     Null deviance: 10066.4  on 16521  degrees of freedom
# Residual deviance:  9567.8  on 16509  degrees of freedom
# AIC: 9593.8
# 
# Number of Fisher Scoring iterations: 6


##getting predicted use as a function of zmax, at average zq60 and zcv
range.hmax <- range(var1$hmax)
range.hmax
#[1] 0.00 99.77

plotting_dfm <- expand.grid(hmax = seq(from = 0, to = 99.7, by = 10),
                            Species    = c("M.brandtii","M.mystacinus"),
                            D7 = mean(var1$D7),
                            gap3.sum.area = mean(var1$gap3.sum.area),
                            gap3.mean.area = mean(var1$gap3.mean.area),
                            gap5.mean.area = mean(var1$gap5.mean.area), 
                            gap5.n = mean(var1$gap5.n))

plotting_dfm$Species = as.factor(plotting_dfm$Species)

plotting_dfm$preds <- plogis( predict(fit.x , newdata=plotting_dfm))

 
##plotting the predicted response on the two covariates
windows()
pl <- ggplot(plotting_dfm, aes(x=hmax, y =preds, color=as.factor(Species)))
pl + 
  geom_point() +
  geom_smooth() + 
  ggtitle("Predicted Use by hmax and Species") + 
  ggplot2::ylab("Predicted Use")


#----------------------------- gap5.n 

##getting predicted use as a function of zq60, at average zmax and zcv
range.gap5.n <- range(var1$gap5.n)
range.gap5.n
#[1] -0.6713285  5.7284651

plotting_dfm <- expand.grid(gap5.n = seq(from = -0.67, to = 5.73, by = 0.2),
                            Species    = c("M.brandtii","M.mystacinus"),
                            D7 = mean(var1$D7),
                            gap3.sum.area = mean(var1$gap3.sum.area),
                            gap3.mean.area = mean(var1$gap3.mean.area),
                            gap5.mean.area = mean(var1$gap5.mean.area), 
                            hmax = mean(var1$hmax))

plotting_dfm$Species = as.factor(plotting_dfm$Species)

plotting_dfm$preds <- plogis( predict(fit.x , newdata=plotting_dfm))


##plotting the predicted response on the two covariates
windows()
pl <- ggplot(plotting_dfm, aes(x=gap5.n, y =preds, color=as.factor(Species)))
pl + 
  geom_point( ) +
  geom_smooth() + 
  ggtitle("Predicted Use by gap5.n and Species") + 
  ggplot2::ylab("Predicted Use")








```


